# Generated by Django 4.2.17 on 2024-12-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTowerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(choices=[(4.8, '4.8m'), (8.0, '8.0m'), (11.2, '11.2m'), (15.4, '15.4m'), (21.0, '21.0m'), (25.5, '25.5m'), (28.0, '28.0m'), (32.1, '32.1m'), (36.6, '36.6m'), (41.0, '41.0m'), (41.01, '41.0.m: над силосами 6.1-6.6'), (41.02, '41.0.m: над силосами 6.7-6.12')], default=0.0, max_length=100)),
            ],
            options={
                'verbose_name': 'Рівень',
                'verbose_name_plural': 'Рівні робочої вежі',
            },
        ),
    ]
