# Generated by Django 4.2.17 on 2024-12-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_tower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('РП-4', 'Substation-4'), ('РП-5', 'Substation-5'), ('РП-6', 'Substation-6'), ('РП-7', 'Substation-7'), ('РП-8', 'Substation-8')], max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_tower.worktowerlevel')),
            ],
            options={
                'verbose_name': 'Підстанція',
                'verbose_name_plural': 'Підстанції',
            },
        ),
    ]
